[theme]
# Primary accent color for interactive elements.
primaryColor =  "#DF6040"

# Background color for the main content area.
backgroundColor = "#1f1f1f"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#252525"

# Color used for almost all text.
textColor = "#B8B8B8"

font="sans serif"